name: base
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - jupyterhub=4.0.2 
  - saspy
  - sas_kernel
  - feather-format
  - jupyterlab
  - jupyterlab-spellchecker
  - nodejs
  - starship
  - beautifulsoup4
  - bottleneck
  - cython
  - dill
  - h5py
  - ipympl
  - ipywidgets
  - jupyterlab-git
  - matplotlib-base
  - numba
  - numexpr
  - openpyxl
  - pandas
  - patsy
  - protobuf
  - pytables
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - sqlalchemy
  - statsmodels
  - sympy
  - widgetsnbextension
  - xlrd
  - openai
  - jupyterlab_code_formatter

# Pip packages
  - pip:
      - dxpy
      - rpy2
      - radian
      - jupyterhub-nativeauthenticator
      - jupyter_ai
      - sos
      - sos-notebook
      - sos-pbs
      - sos-sas
      - sos-python
      - sos-r
      - sos-javascript
      - sos-bash
      



